FROM gcc:latest
COPY . /usr/src/ass1_q2                                                                                 
WORKDIR usr/src/ass1_q2                                                                                  
RUN g++ -o ass1_q2 main.cpp
CMD ["./ass1_q2"]
