FROM httpd:2.4
# Creating the directory ELL887 inside htdocs and then writing the file
RUN mkdir /usr/local/apache2/htdocs/ELL887/ && echo 'Hello World! I am RITIKA SONI' > /usr/local/apache2/htdocs/ELL887/index.html